// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/anime-detail": {
            "get": {
                "description": "Mengambil detail anime, film, atau series termasuk episode, sinopsis, dan rekomendasi. Slug dapat berupa 'nama-anime', 'film/nama-film', atau 'series/nama-series'",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime-detail"
                ],
                "summary": "Get anime/movie/series detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Anime/Movie/Series slug (contoh: 'kobane-2022', 'film/kobane-2022', 'series/legend-of-the-female-general')",
                        "name": "anime_slug",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/anime-terbaru": {
            "get": {
                "description": "Mengambil daftar anime terbaru dengan pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "anime-terbaru"
                ],
                "summary": "Get anime terbaru",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Nomor halaman",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OngoingDramaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/episode-detail": {
            "get": {
                "description": "Mengambil detail episode termasuk server streaming dan link download",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "episode-detail"
                ],
                "summary": "Get episode detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL episode",
                        "name": "episode_url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EpisodeDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/home": {
            "get": {
                "description": "Mengambil data homepage termasuk top 10 anime, episode terbaru, film terbaru, dan jadwal rilis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Home"
                ],
                "summary": "Get homepage data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FinalResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/jadwal-rilis": {
            "get": {
                "description": "Mengambil jadwal rilis anime per hari",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal-rilis"
                ],
                "summary": "Get jadwal rilis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ReleaseScheduleResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/jadwal-rilis/{day}": {
            "get": {
                "description": "Mengambil jadwal rilis anime untuk hari tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal-rilis"
                ],
                "summary": "Get jadwal rilis by day",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama hari (monday, tuesday, wednesday, thursday, friday, saturday, sunday)",
                        "name": "day",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleByDayResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/movie": {
            "get": {
                "description": "Mengambil daftar film dengan pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Get movies",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Nomor halaman",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DramaListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "description": "Mencari anime berdasarkan judul",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search anime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Query pencarian",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Nomor halaman (default: 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AnimeInfo": {
            "type": "object",
            "properties": {
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "synopsis": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.DetailResponse": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "confidence_score": {
                    "type": "number"
                },
                "cover": {
                    "type": "string"
                },
                "details": {
                    "$ref": "#/definitions/models.DetailsObject"
                },
                "episode_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EpisodeItem"
                    }
                },
                "genre": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "judul": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "penonton": {
                    "type": "string"
                },
                "rating": {
                    "$ref": "#/definitions/models.RatingObject"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RecommendationItem"
                    }
                },
                "sinopsis": {
                    "type": "string"
                },
                "skor": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tipe": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.DetailsObject": {
            "type": "object",
            "properties": {
                "Duration": {
                    "type": "string"
                },
                "English": {
                    "type": "string"
                },
                "Japanese": {
                    "type": "string"
                },
                "Producers": {
                    "type": "string"
                },
                "Released:": {
                    "type": "string"
                },
                "Season": {
                    "type": "string"
                },
                "Source": {
                    "type": "string"
                },
                "Status": {
                    "type": "string"
                },
                "Studio": {
                    "type": "string"
                },
                "Total Episode": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                }
            }
        },
        "models.DownloadLinks": {
            "type": "object",
            "properties": {
                "MKV": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.DownloadProvider"
                        }
                    }
                },
                "MP4": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.DownloadProvider"
                        }
                    }
                },
                "x265 [Mode Irit Kuota tapi Kualitas Sama Beningnya]": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.DownloadProvider"
                        }
                    }
                }
            }
        },
        "models.DownloadProvider": {
            "type": "object",
            "properties": {
                "provider": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.DramaDetail": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "judul": {
                    "type": "string"
                },
                "sinopsis": {
                    "type": "string"
                },
                "skor": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "views": {
                    "type": "string"
                }
            }
        },
        "models.DramaEntry": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "episode": {
                    "type": "string"
                },
                "judul": {
                    "type": "string"
                },
                "rilis": {
                    "type": "string"
                },
                "uploader": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.DramaListResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DramaDetail"
                    }
                },
                "message": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.EpisodeDetailResponse": {
            "type": "object",
            "properties": {
                "anime_info": {
                    "$ref": "#/definitions/models.AnimeInfo"
                },
                "confidence_score": {
                    "type": "number"
                },
                "download_links": {
                    "$ref": "#/definitions/models.DownloadLinks"
                },
                "message": {
                    "type": "string"
                },
                "navigation": {
                    "$ref": "#/definitions/models.Navigation"
                },
                "other_episodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OtherEpisode"
                    }
                },
                "release_info": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "streaming_servers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StreamingServer"
                    }
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.EpisodeItem": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "string"
                },
                "episode_slug": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.FinalResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "jadwal_rilis": {
                    "$ref": "#/definitions/models.JadwalRilis"
                },
                "message": {
                    "type": "string"
                },
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MovieItem"
                    }
                },
                "new_eps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NewEpsItem"
                    }
                },
                "source": {
                    "type": "string"
                },
                "top10": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Top10Item"
                    }
                }
            }
        },
        "models.JadwalItem": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover_url": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "release_time": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.JadwalRilis": {
            "type": "object",
            "properties": {
                "Friday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                },
                "Monday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                },
                "Saturday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                },
                "Sunday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                },
                "Thursday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                },
                "Tuesday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                },
                "Wednesday": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalItem"
                    }
                }
            }
        },
        "models.MovieItem": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "judul": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.Navigation": {
            "type": "object",
            "properties": {
                "all_episodes_url": {
                    "type": "string"
                },
                "next_episode_url": {
                    "type": "string"
                },
                "previous_episode_url": {
                    "type": "string"
                }
            }
        },
        "models.NewEpsItem": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "episode": {
                    "type": "string"
                },
                "judul": {
                    "type": "string"
                },
                "rilis": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.OngoingDramaResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DramaEntry"
                    }
                },
                "message": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.OtherEpisode": {
            "type": "object",
            "properties": {
                "release_date": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.RatingObject": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "string"
                },
                "users": {
                    "type": "string"
                }
            }
        },
        "models.RecommendationItem": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover_url": {
                    "type": "string"
                },
                "episode": {
                    "type": "string"
                },
                "rating": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.ReleaseEntry": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover_url": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "release_time": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.ReleaseScheduleResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.ReleaseEntry"
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.ScheduleByDayResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ScheduleEntry"
                    }
                },
                "message": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.ScheduleEntry": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover_url": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "release_time": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.SearchDetail": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "genre": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "judul": {
                    "type": "string"
                },
                "penonton": {
                    "type": "string"
                },
                "sinopsis": {
                    "type": "string"
                },
                "skor": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tipe": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.SearchResponse": {
            "type": "object",
            "properties": {
                "confidence_score": {
                    "type": "number"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SearchDetail"
                    }
                },
                "message": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "models.StreamingServer": {
            "type": "object",
            "properties": {
                "server_name": {
                    "type": "string"
                },
                "streaming_url": {
                    "type": "string"
                }
            }
        },
        "models.Top10Item": {
            "type": "object",
            "properties": {
                "anime_slug": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "judul": {
                    "type": "string"
                },
                "rating": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DramaQu API",
	Description:      "API untuk scraping data drama Korea dari dramaqu.ad",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
